package it.bluesheep.telegrambot;

public enum ChatBotCommand {
	
	ADD_PREFERENCE_BONUS_ABUSING,
	DELETE_PREFERENCE_BONUS_ABUSING,
	SHOW_PREFERENCES_BONUS_ABUSING,
	ENABLE_DISABLE_PREFERENCES_BONUS_ABUSING,
	MOD_PREFERENCES_BONUS_ABUSING,
	RF_BONUS_ABUSING,
	RATING_BONUS_ABUSING,
	EVENT_BONUS_ABUSING,
	MINVALUEODD_BONUS_ABUSING,
	CHAMPIONSHIP_BONUS_ABUSING,
	SIZE_BONUS_ABUSING;

}
